chore: update workflow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -21,19 +21,18 @@ defaults:
     working-directory: ./ # Ensure bun install runs in the correct working directory
 
 jobs:
-  on-failure:
-    runs-on: ubuntu-latest
-    if: ${{ github.event.workflow_run.conclusion == 'failure' }} 
-    steps:
-      - name: Failed workflow
-        run: |
-          echo "Code checks workflow failed"
-          exit 1
+  # on-failure:
+  #   runs-on: ubuntu-latest
+    
+  #   steps:
+  #     - name: Failed workflow
+  #       run: |
+  #         echo "Code checks workflow failed"
+  #         exit 1
 
   setup:
+    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
     runs-on: ubuntu-latest
-    needs: 
-      - on-failure
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -56,10 +55,10 @@ jobs:
           key: ${{ hashFiles('**/bun.lock') }}
 
   publish:
+    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
     runs-on: ubuntu-latest
     needs:
       - setup
-
     permissions:
       contents: write # allow GITHUB_TOKEN to create release
       packages: write # allow GITHUB_TOKEN to publish packages
